---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine/git
    tag: "latest"

inputs:
  - name: source-code

outputs:
  - name: tag-code

run:
  path: ./ci/scripts/set-tag.sh
  dir: source-code
